package rekordbox

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"

	nulltype "github.com/mattn/go-nulltype"
)

// DjmdCloudFilterPlaylist represents a row from 'djmdCloudFilterPlaylist'.
type DjmdCloudFilterPlaylist struct {
	ID                nulltype.NullString `json:"id"`                   // ID
	PlaylistUUID      nulltype.NullString `json:"playlist_uuid"`        // PlaylistUUID
	Seq               nulltype.NullInt64  `json:"seq"`                  // Seq
	ParentID          nulltype.NullString `json:"parent_id"`            // ParentID
	UUID              nulltype.NullString `json:"uuid"`                 // UUID
	RbDataStatus      nulltype.NullInt64  `json:"rb_data_status"`       // rb_data_status
	RbLocalDataStatus nulltype.NullInt64  `json:"rb_local_data_status"` // rb_local_data_status
	RbLocalDeleted    nulltype.NullInt64  `json:"rb_local_deleted"`     // rb_local_deleted
	RbLocalSynced     nulltype.NullInt64  `json:"rb_local_synced"`      // rb_local_synced
	Usn               nulltype.NullInt64  `json:"usn"`                  // usn
	RbLocalUsn        nulltype.NullInt64  `json:"rb_local_usn"`         // rb_local_usn
	CreatedAt         Time                `json:"created_at"`           // created_at
	UpdatedAt         Time                `json:"updated_at"`           // updated_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the DjmdCloudFilterPlaylist exists in the database.
func (dcfp *DjmdCloudFilterPlaylist) Exists() bool {
	return dcfp._exists
}

// Deleted returns true when the DjmdCloudFilterPlaylist has been marked for deletion from
// the database.
func (dcfp *DjmdCloudFilterPlaylist) Deleted() bool {
	return dcfp._deleted
}

// Insert inserts the DjmdCloudFilterPlaylist to the database.
func (c *Client) InsertDjmdCloudFilterPlaylist(ctx context.Context, dcfp *DjmdCloudFilterPlaylist) error {
	db := c.db

	switch {
	case dcfp._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case dcfp._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO djmdCloudFilterPlaylist (` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13` +
		`)`
	// run
	logf(sqlstr, dcfp.ID, dcfp.PlaylistUUID, dcfp.Seq, dcfp.ParentID, dcfp.UUID, dcfp.RbDataStatus, dcfp.RbLocalDataStatus, dcfp.RbLocalDeleted, dcfp.RbLocalSynced, dcfp.Usn, dcfp.RbLocalUsn, dcfp.CreatedAt, dcfp.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, dcfp.ID, dcfp.PlaylistUUID, dcfp.Seq, dcfp.ParentID, dcfp.UUID, dcfp.RbDataStatus, dcfp.RbLocalDataStatus, dcfp.RbLocalDeleted, dcfp.RbLocalSynced, dcfp.Usn, dcfp.RbLocalUsn, dcfp.CreatedAt, dcfp.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	dcfp._exists = true
	return nil
}

// Update updates a DjmdCloudFilterPlaylist in the database.
func (c *Client) UpdateDjmdCloudFilterPlaylist(ctx context.Context, dcfp *DjmdCloudFilterPlaylist) error {
	db := c.db

	switch {
	case !dcfp._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case dcfp._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE djmdCloudFilterPlaylist SET ` +
		`PlaylistUUID = $1, Seq = $2, ParentID = $3, UUID = $4, rb_data_status = $5, rb_local_data_status = $6, rb_local_deleted = $7, rb_local_synced = $8, usn = $9, rb_local_usn = $10, created_at = $11, updated_at = $12 ` +
		`WHERE ID = $13`
	// run
	logf(sqlstr, dcfp.PlaylistUUID, dcfp.Seq, dcfp.ParentID, dcfp.UUID, dcfp.RbDataStatus, dcfp.RbLocalDataStatus, dcfp.RbLocalDeleted, dcfp.RbLocalSynced, dcfp.Usn, dcfp.RbLocalUsn, dcfp.CreatedAt, dcfp.UpdatedAt, dcfp.ID)
	if _, err := db.ExecContext(ctx, sqlstr, dcfp.PlaylistUUID, dcfp.Seq, dcfp.ParentID, dcfp.UUID, dcfp.RbDataStatus, dcfp.RbLocalDataStatus, dcfp.RbLocalDeleted, dcfp.RbLocalSynced, dcfp.Usn, dcfp.RbLocalUsn, dcfp.CreatedAt, dcfp.UpdatedAt, dcfp.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the DjmdCloudFilterPlaylist to the database.
func (c *Client) SaveDjmdCloudFilterPlaylist(ctx context.Context, dcfp *DjmdCloudFilterPlaylist) error {
	if dcfp.Exists() {
		return c.UpdateDjmdCloudFilterPlaylist(ctx, dcfp)
	}
	return c.InsertDjmdCloudFilterPlaylist(ctx, dcfp)
}

// Upsert performs an upsert for DjmdCloudFilterPlaylist.
func (c *Client) UpsertDjmdCloudFilterPlaylist(ctx context.Context, dcfp *DjmdCloudFilterPlaylist) error {
	db := c.db

	switch {
	case dcfp._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO djmdCloudFilterPlaylist (` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13` +
		`)` +
		` ON CONFLICT (ID) DO ` +
		`UPDATE SET ` +
		`PlaylistUUID = EXCLUDED.PlaylistUUID, Seq = EXCLUDED.Seq, ParentID = EXCLUDED.ParentID, UUID = EXCLUDED.UUID, rb_data_status = EXCLUDED.rb_data_status, rb_local_data_status = EXCLUDED.rb_local_data_status, rb_local_deleted = EXCLUDED.rb_local_deleted, rb_local_synced = EXCLUDED.rb_local_synced, usn = EXCLUDED.usn, rb_local_usn = EXCLUDED.rb_local_usn, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at `
	// run
	logf(sqlstr, dcfp.ID, dcfp.PlaylistUUID, dcfp.Seq, dcfp.ParentID, dcfp.UUID, dcfp.RbDataStatus, dcfp.RbLocalDataStatus, dcfp.RbLocalDeleted, dcfp.RbLocalSynced, dcfp.Usn, dcfp.RbLocalUsn, dcfp.CreatedAt, dcfp.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, dcfp.ID, dcfp.PlaylistUUID, dcfp.Seq, dcfp.ParentID, dcfp.UUID, dcfp.RbDataStatus, dcfp.RbLocalDataStatus, dcfp.RbLocalDeleted, dcfp.RbLocalSynced, dcfp.Usn, dcfp.RbLocalUsn, dcfp.CreatedAt, dcfp.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	dcfp._exists = true
	return nil
}

// Delete deletes the DjmdCloudFilterPlaylist from the database.
func (c *Client) DeleteDjmdCloudFilterPlaylist(ctx context.Context, dcfp *DjmdCloudFilterPlaylist) error {
	db := c.db

	switch {
	case !dcfp._exists: // doesn't exist
		return nil
	case dcfp._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM djmdCloudFilterPlaylist ` +
		`WHERE ID = $1`
	// run
	logf(sqlstr, dcfp.ID)
	if _, err := db.ExecContext(ctx, sqlstr, dcfp.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	dcfp._deleted = true
	return nil
}

func scanDjmdCloudFilterPlaylistRows(rows *sql.Rows) ([]*DjmdCloudFilterPlaylist, error) {
	var res []*DjmdCloudFilterPlaylist
	for rows.Next() {
		dcfp := DjmdCloudFilterPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcfp)
	}

	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

func (c *Client) AllDjmdCloudFilterPlaylist(ctx context.Context) ([]*DjmdCloudFilterPlaylist, error) {
	db := c.db

	const sqlstr = `SELECT * FROM DjmdCloudFilterPlaylist`
	rows, err := db.QueryContext(ctx, sqlstr)
	if err != nil {
		return nil, logerror(err)
	}

	defer rows.Close()
	res, err := scanDjmdCloudFilterPlaylistRows(rows)
	if err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudFilterPlaylistByUUID retrieves a row from 'djmdCloudFilterPlaylist' as a DjmdCloudFilterPlaylist.
//
// Generated from index 'djmd_cloud_filter_playlist__u_u_i_d'.
func (c *Client) DjmdCloudFilterPlaylistByUUID(ctx context.Context, uuid nulltype.NullString) ([]*DjmdCloudFilterPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudFilterPlaylist ` +
		`WHERE UUID = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudFilterPlaylist
	for rows.Next() {
		dcfp := DjmdCloudFilterPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcfp)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudFilterPlaylistByRbDataStatus retrieves a row from 'djmdCloudFilterPlaylist' as a DjmdCloudFilterPlaylist.
//
// Generated from index 'djmd_cloud_filter_playlist_rb_data_status'.
func (c *Client) DjmdCloudFilterPlaylistByRbDataStatus(ctx context.Context, rbDataStatus nulltype.NullInt64) ([]*DjmdCloudFilterPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudFilterPlaylist ` +
		`WHERE rb_data_status = $1`
	// run
	logf(sqlstr, rbDataStatus)
	rows, err := db.QueryContext(ctx, sqlstr, rbDataStatus)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudFilterPlaylist
	for rows.Next() {
		dcfp := DjmdCloudFilterPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcfp)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudFilterPlaylistByRbLocalDataStatus retrieves a row from 'djmdCloudFilterPlaylist' as a DjmdCloudFilterPlaylist.
//
// Generated from index 'djmd_cloud_filter_playlist_rb_local_data_status'.
func (c *Client) DjmdCloudFilterPlaylistByRbLocalDataStatus(ctx context.Context, rbLocalDataStatus nulltype.NullInt64) ([]*DjmdCloudFilterPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudFilterPlaylist ` +
		`WHERE rb_local_data_status = $1`
	// run
	logf(sqlstr, rbLocalDataStatus)
	rows, err := db.QueryContext(ctx, sqlstr, rbLocalDataStatus)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudFilterPlaylist
	for rows.Next() {
		dcfp := DjmdCloudFilterPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcfp)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudFilterPlaylistByRbLocalDeleted retrieves a row from 'djmdCloudFilterPlaylist' as a DjmdCloudFilterPlaylist.
//
// Generated from index 'djmd_cloud_filter_playlist_rb_local_deleted'.
func (c *Client) DjmdCloudFilterPlaylistByRbLocalDeleted(ctx context.Context, rbLocalDeleted nulltype.NullInt64) ([]*DjmdCloudFilterPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudFilterPlaylist ` +
		`WHERE rb_local_deleted = $1`
	// run
	logf(sqlstr, rbLocalDeleted)
	rows, err := db.QueryContext(ctx, sqlstr, rbLocalDeleted)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudFilterPlaylist
	for rows.Next() {
		dcfp := DjmdCloudFilterPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcfp)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudFilterPlaylistByRbLocalUsnID retrieves a row from 'djmdCloudFilterPlaylist' as a DjmdCloudFilterPlaylist.
//
// Generated from index 'djmd_cloud_filter_playlist_rb_local_usn__i_d'.
func (c *Client) DjmdCloudFilterPlaylistByRbLocalUsnID(ctx context.Context, rbLocalUsn nulltype.NullInt64, id nulltype.NullString) ([]*DjmdCloudFilterPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudFilterPlaylist ` +
		`WHERE rb_local_usn = $1 AND ID = $2`
	// run
	logf(sqlstr, rbLocalUsn, id)
	rows, err := db.QueryContext(ctx, sqlstr, rbLocalUsn, id)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudFilterPlaylist
	for rows.Next() {
		dcfp := DjmdCloudFilterPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcfp)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudFilterPlaylistByID retrieves a row from 'djmdCloudFilterPlaylist' as a DjmdCloudFilterPlaylist.
//
// Generated from index 'sqlite_autoindex_djmdCloudFilterPlaylist_1'.
func (c *Client) DjmdCloudFilterPlaylistByID(ctx context.Context, id nulltype.NullString) (*DjmdCloudFilterPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, PlaylistUUID, Seq, ParentID, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudFilterPlaylist ` +
		`WHERE ID = $1`
	// run
	logf(sqlstr, id)
	dcfp := DjmdCloudFilterPlaylist{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&dcfp.ID, &dcfp.PlaylistUUID, &dcfp.Seq, &dcfp.ParentID, &dcfp.UUID, &dcfp.RbDataStatus, &dcfp.RbLocalDataStatus, &dcfp.RbLocalDeleted, &dcfp.RbLocalSynced, &dcfp.Usn, &dcfp.RbLocalUsn, &dcfp.CreatedAt, &dcfp.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &dcfp, nil
}
