package rekordbox

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"

	nulltype "github.com/mattn/go-nulltype"
)

// DjmdCloudExportPlaylist represents a row from 'djmdCloudExportPlaylist'.
type DjmdCloudExportPlaylist struct {
	ID                nulltype.NullString `json:"id"`                   // ID
	Seq               nulltype.NullInt64  `json:"seq"`                  // Seq
	Name              nulltype.NullString `json:"name"`                 // Name
	ImagePath         nulltype.NullString `json:"image_path"`           // ImagePath
	Attribute         nulltype.NullInt64  `json:"attribute"`            // Attribute
	ParentID          nulltype.NullString `json:"parent_id"`            // ParentID
	SmartList         nulltype.NullString `json:"smart_list"`           // SmartList
	UUID              nulltype.NullString `json:"uuid"`                 // UUID
	RbDataStatus      nulltype.NullInt64  `json:"rb_data_status"`       // rb_data_status
	RbLocalDataStatus nulltype.NullInt64  `json:"rb_local_data_status"` // rb_local_data_status
	RbLocalDeleted    nulltype.NullInt64  `json:"rb_local_deleted"`     // rb_local_deleted
	RbLocalSynced     nulltype.NullInt64  `json:"rb_local_synced"`      // rb_local_synced
	Usn               nulltype.NullInt64  `json:"usn"`                  // usn
	RbLocalUsn        nulltype.NullInt64  `json:"rb_local_usn"`         // rb_local_usn
	CreatedAt         Time                `json:"created_at"`           // created_at
	UpdatedAt         Time                `json:"updated_at"`           // updated_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the DjmdCloudExportPlaylist exists in the database.
func (dcep *DjmdCloudExportPlaylist) Exists() bool {
	return dcep._exists
}

// Deleted returns true when the DjmdCloudExportPlaylist has been marked for deletion from
// the database.
func (dcep *DjmdCloudExportPlaylist) Deleted() bool {
	return dcep._deleted
}

// Insert inserts the DjmdCloudExportPlaylist to the database.
func (c *Client) InsertDjmdCloudExportPlaylist(ctx context.Context, dcep *DjmdCloudExportPlaylist) error {
	db := c.db

	switch {
	case dcep._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case dcep._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO djmdCloudExportPlaylist (` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16` +
		`)`
	// run
	logf(sqlstr, dcep.ID, dcep.Seq, dcep.Name, dcep.ImagePath, dcep.Attribute, dcep.ParentID, dcep.SmartList, dcep.UUID, dcep.RbDataStatus, dcep.RbLocalDataStatus, dcep.RbLocalDeleted, dcep.RbLocalSynced, dcep.Usn, dcep.RbLocalUsn, dcep.CreatedAt, dcep.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, dcep.ID, dcep.Seq, dcep.Name, dcep.ImagePath, dcep.Attribute, dcep.ParentID, dcep.SmartList, dcep.UUID, dcep.RbDataStatus, dcep.RbLocalDataStatus, dcep.RbLocalDeleted, dcep.RbLocalSynced, dcep.Usn, dcep.RbLocalUsn, dcep.CreatedAt, dcep.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	dcep._exists = true
	return nil
}

// Update updates a DjmdCloudExportPlaylist in the database.
func (c *Client) UpdateDjmdCloudExportPlaylist(ctx context.Context, dcep *DjmdCloudExportPlaylist) error {
	db := c.db

	switch {
	case !dcep._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case dcep._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE djmdCloudExportPlaylist SET ` +
		`Seq = $1, Name = $2, ImagePath = $3, Attribute = $4, ParentID = $5, SmartList = $6, UUID = $7, rb_data_status = $8, rb_local_data_status = $9, rb_local_deleted = $10, rb_local_synced = $11, usn = $12, rb_local_usn = $13, created_at = $14, updated_at = $15 ` +
		`WHERE ID = $16`
	// run
	logf(sqlstr, dcep.Seq, dcep.Name, dcep.ImagePath, dcep.Attribute, dcep.ParentID, dcep.SmartList, dcep.UUID, dcep.RbDataStatus, dcep.RbLocalDataStatus, dcep.RbLocalDeleted, dcep.RbLocalSynced, dcep.Usn, dcep.RbLocalUsn, dcep.CreatedAt, dcep.UpdatedAt, dcep.ID)
	if _, err := db.ExecContext(ctx, sqlstr, dcep.Seq, dcep.Name, dcep.ImagePath, dcep.Attribute, dcep.ParentID, dcep.SmartList, dcep.UUID, dcep.RbDataStatus, dcep.RbLocalDataStatus, dcep.RbLocalDeleted, dcep.RbLocalSynced, dcep.Usn, dcep.RbLocalUsn, dcep.CreatedAt, dcep.UpdatedAt, dcep.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the DjmdCloudExportPlaylist to the database.
func (c *Client) SaveDjmdCloudExportPlaylist(ctx context.Context, dcep *DjmdCloudExportPlaylist) error {
	if dcep.Exists() {
		return c.UpdateDjmdCloudExportPlaylist(ctx, dcep)
	}
	return c.InsertDjmdCloudExportPlaylist(ctx, dcep)
}

// Upsert performs an upsert for DjmdCloudExportPlaylist.
func (c *Client) UpsertDjmdCloudExportPlaylist(ctx context.Context, dcep *DjmdCloudExportPlaylist) error {
	db := c.db

	switch {
	case dcep._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO djmdCloudExportPlaylist (` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16` +
		`)` +
		` ON CONFLICT (ID) DO ` +
		`UPDATE SET ` +
		`Seq = EXCLUDED.Seq, Name = EXCLUDED.Name, ImagePath = EXCLUDED.ImagePath, Attribute = EXCLUDED.Attribute, ParentID = EXCLUDED.ParentID, SmartList = EXCLUDED.SmartList, UUID = EXCLUDED.UUID, rb_data_status = EXCLUDED.rb_data_status, rb_local_data_status = EXCLUDED.rb_local_data_status, rb_local_deleted = EXCLUDED.rb_local_deleted, rb_local_synced = EXCLUDED.rb_local_synced, usn = EXCLUDED.usn, rb_local_usn = EXCLUDED.rb_local_usn, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at `
	// run
	logf(sqlstr, dcep.ID, dcep.Seq, dcep.Name, dcep.ImagePath, dcep.Attribute, dcep.ParentID, dcep.SmartList, dcep.UUID, dcep.RbDataStatus, dcep.RbLocalDataStatus, dcep.RbLocalDeleted, dcep.RbLocalSynced, dcep.Usn, dcep.RbLocalUsn, dcep.CreatedAt, dcep.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, dcep.ID, dcep.Seq, dcep.Name, dcep.ImagePath, dcep.Attribute, dcep.ParentID, dcep.SmartList, dcep.UUID, dcep.RbDataStatus, dcep.RbLocalDataStatus, dcep.RbLocalDeleted, dcep.RbLocalSynced, dcep.Usn, dcep.RbLocalUsn, dcep.CreatedAt, dcep.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	dcep._exists = true
	return nil
}

// Delete deletes the DjmdCloudExportPlaylist from the database.
func (c *Client) DeleteDjmdCloudExportPlaylist(ctx context.Context, dcep *DjmdCloudExportPlaylist) error {
	db := c.db

	switch {
	case !dcep._exists: // doesn't exist
		return nil
	case dcep._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM djmdCloudExportPlaylist ` +
		`WHERE ID = $1`
	// run
	logf(sqlstr, dcep.ID)
	if _, err := db.ExecContext(ctx, sqlstr, dcep.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	dcep._deleted = true
	return nil
}

func scanDjmdCloudExportPlaylistRows(rows *sql.Rows) ([]*DjmdCloudExportPlaylist, error) {
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}

	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

func (c *Client) AllDjmdCloudExportPlaylist(ctx context.Context) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	const sqlstr = `SELECT * FROM DjmdCloudExportPlaylist`
	rows, err := db.QueryContext(ctx, sqlstr)
	if err != nil {
		return nil, logerror(err)
	}

	defer rows.Close()
	res, err := scanDjmdCloudExportPlaylistRows(rows)
	if err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByAttribute retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist__attribute'.
func (c *Client) DjmdCloudExportPlaylistByAttribute(ctx context.Context, attribute nulltype.NullInt64) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE Attribute = $1`
	// run
	logf(sqlstr, attribute)
	rows, err := db.QueryContext(ctx, sqlstr, attribute)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByName retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist__name'.
func (c *Client) DjmdCloudExportPlaylistByName(ctx context.Context, name nulltype.NullString) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE Name = $1`
	// run
	logf(sqlstr, name)
	rows, err := db.QueryContext(ctx, sqlstr, name)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByParentID retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist__parent_i_d'.
func (c *Client) DjmdCloudExportPlaylistByParentID(ctx context.Context, parentID nulltype.NullString) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE ParentID = $1`
	// run
	logf(sqlstr, parentID)
	rows, err := db.QueryContext(ctx, sqlstr, parentID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistBySeq retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist__seq'.
func (c *Client) DjmdCloudExportPlaylistBySeq(ctx context.Context, seq nulltype.NullInt64) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE Seq = $1`
	// run
	logf(sqlstr, seq)
	rows, err := db.QueryContext(ctx, sqlstr, seq)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByUUID retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist__u_u_i_d'.
func (c *Client) DjmdCloudExportPlaylistByUUID(ctx context.Context, uuid nulltype.NullString) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE UUID = $1`
	// run
	logf(sqlstr, uuid)
	rows, err := db.QueryContext(ctx, sqlstr, uuid)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByRbDataStatus retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist_rb_data_status'.
func (c *Client) DjmdCloudExportPlaylistByRbDataStatus(ctx context.Context, rbDataStatus nulltype.NullInt64) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE rb_data_status = $1`
	// run
	logf(sqlstr, rbDataStatus)
	rows, err := db.QueryContext(ctx, sqlstr, rbDataStatus)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByRbLocalDataStatus retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist_rb_local_data_status'.
func (c *Client) DjmdCloudExportPlaylistByRbLocalDataStatus(ctx context.Context, rbLocalDataStatus nulltype.NullInt64) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE rb_local_data_status = $1`
	// run
	logf(sqlstr, rbLocalDataStatus)
	rows, err := db.QueryContext(ctx, sqlstr, rbLocalDataStatus)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByRbLocalDeleted retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist_rb_local_deleted'.
func (c *Client) DjmdCloudExportPlaylistByRbLocalDeleted(ctx context.Context, rbLocalDeleted nulltype.NullInt64) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE rb_local_deleted = $1`
	// run
	logf(sqlstr, rbLocalDeleted)
	rows, err := db.QueryContext(ctx, sqlstr, rbLocalDeleted)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByRbLocalUsnID retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'djmd_cloud_export_playlist_rb_local_usn__i_d'.
func (c *Client) DjmdCloudExportPlaylistByRbLocalUsnID(ctx context.Context, rbLocalUsn nulltype.NullInt64, id nulltype.NullString) ([]*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE rb_local_usn = $1 AND ID = $2`
	// run
	logf(sqlstr, rbLocalUsn, id)
	rows, err := db.QueryContext(ctx, sqlstr, rbLocalUsn, id)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*DjmdCloudExportPlaylist
	for rows.Next() {
		dcep := DjmdCloudExportPlaylist{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &dcep)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// DjmdCloudExportPlaylistByID retrieves a row from 'djmdCloudExportPlaylist' as a DjmdCloudExportPlaylist.
//
// Generated from index 'sqlite_autoindex_djmdCloudExportPlaylist_1'.
func (c *Client) DjmdCloudExportPlaylistByID(ctx context.Context, id nulltype.NullString) (*DjmdCloudExportPlaylist, error) {
	db := c.db

	// query
	const sqlstr = `SELECT ` +
		`ID, Seq, Name, ImagePath, Attribute, ParentID, SmartList, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at ` +
		`FROM djmdCloudExportPlaylist ` +
		`WHERE ID = $1`
	// run
	logf(sqlstr, id)
	dcep := DjmdCloudExportPlaylist{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&dcep.ID, &dcep.Seq, &dcep.Name, &dcep.ImagePath, &dcep.Attribute, &dcep.ParentID, &dcep.SmartList, &dcep.UUID, &dcep.RbDataStatus, &dcep.RbLocalDataStatus, &dcep.RbLocalDeleted, &dcep.RbLocalSynced, &dcep.Usn, &dcep.RbLocalUsn, &dcep.CreatedAt, &dcep.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &dcep, nil
}
